name: CD
 
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '19.x'
    - run: npm install
    - run: npm run build
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.itsourov.com
        username: u440599207.laravel
        password: ${{ secrets.ftp_password }}

    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: u440599207
        host: 195.179.238.26
        password: ${{ secrets.ftp_password }}
        port: 65002
        script: 'cd /home/u440599207/domains/itsourov.com/public_html/igse && ./server_deploy.sh'